name: CI/CD Deploy CLIYNIC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repo
      uses: actions/checkout@v3

    # Setup Node.js versi terbaru sesuai requirement (>=20)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Disable strict engine check (untuk menghindari EBADENGINE)
    - name: Disable strict engines
      run: npm config set engine-strict false

    # ==== Build Frontend ====
    - name: Install dependencies frontend
      run: |
        cd frontend
        npm ci || npm install
        npm run build

    # ==== Install Backend Dependencies ====
    - name: Install dependencies backend
      run: |
        cd backend
        npm ci || npm install

    # ==== Deploy Frontend to EC2 ====
    - name: Deploy Frontend to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_FE_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "frontend/build/*"
        target: "/home/ubuntu/cc-cliynic/frontend/build"

    # ==== Deploy Backend to EC2 ====
    - name: Deploy Backend to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_BE_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "backend/*"
        target: "/home/ubuntu/cc-cliynic/backend"

    # ==== Restart Docker Backend ====
    - name: Restart Backend Docker
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_BE_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/cc-cliynic/backend
          sudo docker stop cc-backend || true
          sudo docker rm cc-backend || true
          sudo docker build -t cc-backend .
          sudo docker run -d --name cc-backend -p 3001:3001 cc-backend

