name: CI/CD Deploy CLIYNIC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ==== 1. Checkout repo ====
    - name: Checkout repo
      uses: actions/checkout@v3

    # ==== 2. Setup Node.js (optional lint/test) ====
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # ==== 3. Install backend dependencies (optional test) ====
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci

    # ==== 4. Copy Backend Code via Bastion ====
    - name: Copy Backend Code via Bastion
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_FE_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "backend/**"
        target: "/home/ubuntu/backend-temp"

    # ==== 5. Deploy & Restart Backend via Bastion ====
    - name: Deploy & Restart Backend via Bastion
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_FE_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Copy backend-temp to backend EC2
          scp -i ~/.ssh/aws_pertama_saya.pem -o StrictHostKeyChecking=no -r /home/ubuntu/backend-temp/* ubuntu@${{ secrets.EC2_BE_HOST }}:/home/ubuntu/cc-cliynic/backend

          # Copy file .env specifically
          scp -i ~/.ssh/aws_pertama_saya.pem -o StrictHostKeyChecking=no /home/ubuntu/backend-temp/.env ubuntu@${{ secrets.EC2_BE_HOST }}:/home/ubuntu/cc-cliynic/backend/.env

          # SSH ke backend dan restart Docker
          ssh -i ~/.ssh/aws_pertama_saya.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_BE_HOST }} << 'EOF'
            cd /home/ubuntu/cc-cliynic/backend
            sudo docker stop cc-backend || true
            sudo docker rm cc-backend || true
            sudo docker build -t cc-backend .
            sudo docker run -d --name cc-backend -p 3001:3001 cc-backend
          EOF

